name: Create Release on Milestone Close

on:
  milestone:
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Milestone Details
        id: milestone_info
        run: |
          MILESTONE="${{ github.event.milestone.title }}"
          echo "MILESTONE=$MILESTONE" >> $GITHUB_ENV

      - name: Extract Changelog for Milestone
        id: extract_changelog
        run: |
          MILESTONE="# $MILESTONE"
          START_LINE=$(grep -n "^$MILESTONE" CHANGELOG.md | cut -d: -f1 | head -n1)

          if [ -z "$START_LINE" ]; then
            echo "Milestone not found in CHANGELOG.md"
            exit 1
          fi

          END_LINE=$(tail -n +$((START_LINE+1)) CHANGELOG.md | grep -n "^#" | head -n1 | cut -d: -f1)
          if [ -z "$END_LINE" ]; then
            END_LINE=$(wc -l < CHANGELOG.md)
          else
            END_LINE=$((START_LINE + END_LINE - 1))
          fi

          sed -n "$((START_LINE+1)),$((END_LINE-1))p" CHANGELOG.md > changelog_excerpt.md

          echo "CHANGELOG_CONTENT"

          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          cat changelog_excerpt.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.MILESTONE }}
          name: Release ${{ env.MILESTONE }}
          body_path: changelog_excerpt.md
          draft: false
          prerelease: false
