on:
  workflow_dispatch: # Allows manual execution

jobs:
  get_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Find milestone from all open milestones
        id: find_milestone
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues?milestone=1&state=closed"

          ISSUES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")

          ISSUE_DATA=$(echo "$ISSUES" | jq -r '.[] | {number: .number, timeline_url: .timeline_url, title: .title, body: .body, user: .user.login}')
          echo "$ISSUE_DATA"
