name: Frequent Milestone Release

on:
  workflow_dispatch: # Allows manual execution

jobs:
  get_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Find milestone from all open milestones
        id: find_milestone
        env:
          MILESTONE_NUMBER: ${{ secrets.MILESTONES_NUM }}
        run: |
          echo "Milestone Number from Secrets: $MILESTONE_NUMBER"
