name: Frequent Milestone Release

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual execution

jobs:
  get_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch issues linked to milestone
        id: fetch_issues
        env:
          MILESTONE_NUMBER: ${{ secrets.MILESTONES_NUM }}
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues?milestone=${{ env.MILESTONE_NUMBER }}&state=closed"
          echo "Fetching issues from: $API_URL"

          ISSUES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")

          ISSUE_NUMBERS=$(echo "$ISSUES" | jq -r '.[] | select(.pull_request == null) | .number')
          PR_NUMBERS=$(echo "$ISSUES" | jq -r '.[] | select(.pull_request != null) | .number')

          if [[ -z "$ISSUE_NUMBERS" || "$ISSUE_NUMBERS" == "null" ]]; then
            ISSUE_NUMBERS="No issues found."
          fi

          if [[ -z "$PR_NUMBERS" || "$PR_NUMBERS" == "null" ]]; then
            PR_NUMBERS="No PRs found."
          fi

          echo "ISSUE_NUMBERS<<EOF" >> $GITHUB_ENV
          echo "$ISSUE_NUMBERS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "PR_NUMBERS<<EOF" >> $GITHUB_ENV
          echo "$PR_NUMBERS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Fetch PR details from linked issues
        id: fetch_prs
        env:
          PR_NUMBERS: ${{ env.PR_NUMBERS }}
        run: |
          if [[ "$PR_NUMBERS" == "No PRs found." ]]; then
            echo "No PRs found linked to issues."
            exit 0
          fi

          PR_LIST=""
          for PR_NUMBER in $PR_NUMBERS; do
            API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
            echo "Fetching PR details from: $API_URL"

            PR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")
            PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
            PR_AUTHOR=$(echo "$PR_DATA" | jq -r '.user.login')
            PR_URL=$(echo "$PR_DATA" | jq -r '.html_url')

            PR_LIST+="* $PR_TITLE by @$PR_AUTHOR in $PR_URL"$'\n'
          done

          echo "PR_LIST<<EOF" >> $GITHUB_ENV
          echo "$PR_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  create_release:
    needs: get_pr_details
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
            echo "Version not found in package.json"
            exit 1
          fi
          echo "version=v$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MILESTONE_NUMBER: ${{ secrets.MILESTONES_NUM }}
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          RELEASE_BODY="$(cat <<EOF
          ## What's Changed
          ${{ env.PR_LIST }}

          ## New Contributors
          ${{ env.NEW_CONTRIBUTORS }}

          **Full Changelog**: ${REPO_URL}/commits/${{ env.version }}
          EOF
          )"

          API_URL="https://api.github.com/repos/${{ github.repository }}/releases"
          echo "Creating release via API: $API_URL"

          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$API_URL" \
            -d '{
              "tag_name": "${{ env.version }}",
              "name": "${{ env.version }}",
              "body": "'"${RELEASE_BODY//$'\n'/'\n'}"'",
              "draft": false,
              "prerelease": false
            }'

          echo "Release created successfully"

  close_milestone:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Close the milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MILESTONE_NUMBER: ${{ secrets.MILESTONES_NUM }}
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/milestones/${{ env.MILESTONE_NUMBER }}"
          echo "Closing milestone using API: $API_URL"

          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$API_URL" \
            -d '{"state": "closed"}'
          
          echo "Milestone closed successfully"
