on:
  workflow_dispatch: # Allows manual execution

jobs:
  get_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Find milestone from all open milestones
        id: find_milestone
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues?milestone=1&state=closed"

          ISSUES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")

          ISSUE_DATA=$(echo "$ISSUES" | jq -c '[.[] | {number: .number, title: .title, body: .body, user: .user.login}]')

          echo "ISSUE_LIST<<EOF" >> $GITHUB_ENV
          echo "$ISSUE_DATA" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Use Saved Issue Data
        env:
          ISSUE_LIST: ${{ env.ISSUE_LIST }}
        run: |
          echo "Using stored issue list:"
          echo "$ISSUE_LIST" | jq .
