name: Frequent Milestone Release

on:
  workflow_dispatch: # Allows manual execution

jobs:
  get_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Find milestone from all open milestones
        id: find_milestone
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues?milestone=1"
          echo "Fetching issues from: $API_URL"

          ISSUES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")
          echo "Fetched issues: $ISSUES"
